spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 指定数据库驱动类
    # 数据库连接信息
    url: jdbc:mysql://192.168.20.101:3306/xiaohongshu?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root # 数据库用户名
    password: A2qT03X7KlL4v/F2foD6kV/Ch9gpNBWOh1qoCywanjv1AsI7f9x3iAyR9NkUKeV+FMo+halCTzy5Llbk2VOrVQ== # 数据库密码
    type: com.alibaba.druid.pool.DruidDataSource
    druid: # Druid 连接池
      initial-size: 5 # 初始化连接池大小
      min-idle: 5 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 60000 # 连接时最大等待时间（单位：毫秒）
      test-while-idle: true
      time-between-eviction-runs-millis: 60000 # 配置多久进行一次检测，检测需要关闭的连接（单位：毫秒）
      min-evictable-idle-time-millis: 300000 # 配置一个连接在连接池中最小生存的时间（单位：毫秒）
      max-evictable-idle-time-millis: 900000 # 配置一个连接在连接池中最大生存的时间（单位：毫秒）
      validation-query: SELECT 1 FROM DUAL # 配置测试连接是否可用的查询 sql
      # TODO
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIaJmhsfN14oM+bghiOfARP6YgIiArekviyAOEa9Dt8spf4W38kSJShGs0NkzT3btqJB0O2o0X/yfVE8kqme1jMCAwEAAQ==
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/* # 配置监控后台访问路径
        login-username: admin # 配置监控后台登录的用户名、密码
        login-password: admin
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          log-slow-sql: true # 开启慢 sql 记录
          slow-sql-millis: 2000 # 若执行耗时大于 2s，则视为慢 sql
          merge-sql: true
        wall: # 防火墙
          config:
            multi-statement-allow: true
            
  data:
    redis:
      database: 0 # Redis 数据库索引
      host: 192.168.20.101 # Redis 服务器地址
      port: 6379 # Redis 服务器端口
      password: 123456 # Redis 密码
      timeout: 5s # Redis 连接超时时间（单位：毫秒）
      connect-timeout: 5s # Redis 连接超时时间（单位：毫秒）
      lettuce:
        pool:
          max-active: 200 # Lettuce 连接池最大活动连接数
          max-wait: -1ms  # Lettuce 连接池最大等待时间（单位：毫秒）
          min-idle: 0 # Lettuce 连接池最小空闲连接数
          max-idle: 200 # Lettuce 连接池最大空闲连接数

logging:
  level:
    com.kaiming.xiaohongshu.note.biz.domain.mapper: debug

rocketmq:
  name-server: 127.0.0.1:9876 # RocketMQ NameServer 地址
  producer:
    group: xiaohongshu_group
    send-message-timeout: 3000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3
    max-message-size: 4096  # 最大消息大小
  consumer:
    group: xiaohongshu_group
    pull-batch-size: 5