spring:
  cassandra:
    keyspace-name: xiaohashu
    contact-points: 192.168.20.101
    port: 9042
    
rocketmq:
  name-server: 127.0.0.1:9876
  consumer:
    group: xiaohongshu_group
    pull-batch-size: 5