server:
  port: 8080  # 项目端口

spring:
  profiles:
    active: dev   # 默认激活dev本地开发环境

#mybatis:
#  mapper-locations: classpath:/mapper/**/*.xml

sa-token:
  token-name: Authorization
  token-prefix: Bearer  # token 前缀
  timeout: 2592000  # token过期时间，单位秒
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  is-log: true

#rate-limit:
#  api:
#    limit: 100  # 接口限流阈值
#
#alarm:
#  type: sms

#nacos:
#  config:
#    access-key:
#    secret-key:
#    data-id: xiaohongshu-auth
#    group: DEFAULT_GROUP
#    type: yaml
#    server-addr: http://192.168.20.101:8848
#    auto-refresh: true
#    remote-first: true
#    bootstrap:
#      enable: true