spring:
  data:
    redis:
      database: 0
      host: 192.168.20.101
      port: 6379
      password: 123456
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 连接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms  # 连接池最大阻塞等待时间，负值表示没限制
          min-idle: 0 # 连接池最小空闲连接数
          max-idle: 10  # 连接池最大空闲连接数
aliyun:
  accessKeyId: 
  accessKeySecret: 